apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pkssc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Retain
parameters:
  datastore: LUN01
  diskformat: thin
  fstype: ext4