global:
  imagePullSecrets:
    - name: regcred

prometheusOperator:
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus-operator
    tag: v0.38.1
  tlsProxy:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/ghostunnel
      tag: v1.5.2
  prometheusConfigReloaderImage:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus-config-reloader
    tag: v0.38.1
  configmapReloadImage:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/configmap-reload
    tag: v0.3.0
  admissionWebhooks:
    patch:
      image:
        repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/kube-webhook-certgen
        tag: v1.2.0

alertmanager:
  alertmanagerSpec:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/alertmanager
      tag: v0.20.0

prometheus:
  prometheusSpec:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus
      tag: v2.17.2

    additionalScrapeConfigs: []
      - job_name: 'federate'
        scrape_interval: 15s
        honor_labels: true
        metrics_path: '/federate'
        params:
          'match[]':
            - '{job="prometheus"}'
            - '{__name__=~"job:.*"}'
        static_configs:
          - targets:
              - '172.28.0.3:30491'

#    additionalScrapeConfigs:
#      - job_name: 'federation'
#        scrape_interval: 1m
#        metrics_path: /federate
#        scrape_timeout: 55s
#        honor_labels: true
#        params:
#          'match[]':
#            - '{job="kube-state-metrics"}'
#            - '{job="apiserver"}'
#            - '{job="kubelet"}'
#        static_configs:
#          - targets:
#              - "172.28.0.3:30491"
#              - "172.28.1.3:30912"


kube-state-metrics:
  serviceAccount:
    imagePullSecrets:
      - name: regcred
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/kube-state-metrics
    tag: v1.9.5

grafana:
  image:
    pullSecrets:
      - regcred
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/grafana
    tag: 6.6.0
  sidecar:
    image: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/k8s-sidecar:0.1.99

prometheus-node-exporter:
  serviceAccount:
    imagePullSecrets:
      - name: regcred
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/node-exporter
    tag: v0.18.1