global:
  imagePullSecrets:
    - name: regcred

prometheusOperator:
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus-operator
    tag: v0.38.1
  tlsProxy:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/ghostunnel
      tag: v1.5.2
  prometheusConfigReloaderImage:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus-config-reloader
    tag: v0.38.1
  configmapReloadImage:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/configmap-reload
    tag: v0.3.0
  admissionWebhooks:
    patch:
      image:
        repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/kube-webhook-certgen
        tag: v1.2.0

alertmanager:
  alertmanagerSpec:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/alertmanager
      tag: v0.20.0

prometheus:
  prometheusSpec:
    image:
      repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/prometheus
      tag: v2.17.2

kube-state-metrics:
  serviceAccount:
    imagePullSecrets:
      - name: regcred
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/kube-state-metrics
    tag: v1.9.5

grafana:
  image:
    pullSecrets:
      - regcred
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/grafana
    tag: 6.6.0
  sidecar:
    image: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/k8s-sidecar:0.1.99

prometheus-node-exporter:
  serviceAccount:
    imagePullSecrets:
      - name: regcred
  image:
    repository: harbor.run.haas-205.pez.pivotal.io/dbha/monitoring/node-exporter
    tag: v0.18.1