apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
  name: mariadb-cluster-metric-sink
spec:
  inputs:
    - type: prometheus
      urls:
        - "http://mariadb-galera-metrics.default:9104/metrics"

  outputs:
    - type: prometheus_client
      listen: ":9104"