apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
  name: nginx-cluster-metric-sink
spec:
  inputs:
  - type: prometheus
    urls: [
      "http://10.100.200.95:9113/metrics"
    ]
  outputs:
  - type: prometheus_client
    listen: ":9113"