apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
  name: wordpress-cluster-metric-sink
spec:
  inputs:
    - type: prometheus
      urls:
        - "http://wordpress-svc.default:9117/metrics"

  outputs:
    - type: prometheus_client
      listen: ":9117"