apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  #  loadBalancerIP: 10.195.70.186
  type: LoadBalancer
#   type: NodePort